### ISSUE TITLE
Make fails when using ARM Toolchain 10-2020-q4-major

### ISSUE THREAD

**Issue by Moll1989** [darksidelemm/RS41FOX#2]
make fails for me when I use the latest version of ARM Toolchain.  Using 8-2018-q4-major seems to work fine.
System is Xubuntu 20.04.2 LTS - Kernel 5.8.0-53-generic.

Attached is a copy of what I am getting in terminal.
[rs41fox-make-stdout-fail.log](https://github.com/darksidelemm/RS41FOX/files/6677473/rs41fox-make-stdout-fail.log)

**Comment by MrARM** [comment]
Not sure if you ever solved your issue, but I stumbled upon the same issue. 
An easy solution is to use arm-none-eabi-7-2017-q4-major, which would've been the compiler this program was built on.

**Comment by argilo** [comment]
I solved this by moving the definition of `ADCVal` into init.c, like so:

```diff
diff --git a/init.c b/init.c
index 5186fbc..c135850 100644
--- a/init.c
+++ b/init.c
@@ -11,6 +11,8 @@
 #include "init.h"
 #include "radio.h"
 
+__IO uint16_t ADCVal[2];
+
 SPI_InitTypeDef   SPI_InitStructure;
 USART_InitTypeDef USART_InitStructure;
 GPIO_InitTypeDef GPIO_Conf;
diff --git a/init.h b/init.h
index 33f47ab..8f6bda6 100644
--- a/init.h
+++ b/init.h
@@ -1,4 +1,4 @@
-__IO uint16_t ADCVal[2];
+extern __IO uint16_t ADCVal[2];
 #ifdef __cplusplus
 extern "C" {
 #endif
```

**Comment by argilo** [comment]
I opened #4 with that fix.
